Repository Haivision/srt, pull requests merged in 2021-09, with the labels that each got.

#2104 Fix Build for MacOS, FreeBSD, GCC earlier than 4.7, and Clang earlier…
  CMakeLists.txt
  srtcore/atomic.h
  srtcore/atomic_clock.h
  srtcore/sync.h
Labels: Type: Bug, [build]

#2116 Generalize libatomic Detection.
  CMakeLists.txt
  scripts/CheckCXXAtomic.cmake
  scripts/CheckGCCAtomicIntrinsics.cmake
Labels: Type: Bug, [build]

#2117 Update Windows installer for alternate platform names
  scripts/win-installer/libsrt.props
Labels: Type: Maintenance, [build]

#2118 [core] Avoid using strlen in ThreadName class
  srtcore/threadname.h
Labels: Type: Maintenance, [core]

#2119 [docs] Improved Access Control general syntax description
  docs/features/access-control.md
Labels: Type: Maintenance, [docs]

#2115 Fix Build on Solaris.
  CMakeLists.txt
  apps/srt-tunnel.cpp
  apps/transmitmedia.cpp
  srtcore/common.cpp
  srtcore/epoll.cpp
  srtcore/list.cpp
  srtcore/srt_compat.c
  srtcore/sync.h
  srtcore/sync_cxx11.cpp
  srtcore/utilities.h
  testing/testactivemedia.cpp
  testing/testactivemedia.hpp
Labels: Type: Maintenance, [core]

#2127 [core] Fixed FileCC random decrease
  srtcore/congctl.cpp
Labels: Type: Bug, [core]

#2123 Fix Build CMake <3.0.2 #2121.
  scripts/CheckCXXAtomic.cmake
  scripts/CheckGCCAtomicIntrinsics.cmake
  scripts/FindPThreadGetSetName.cmake
  scripts/UnSetVariableFull.cmake
Labels: Type: Bug, [build]

#2128 [build] Build but do not install test-srt
  CMakeLists.txt
Labels: Type: Maintenance, [build]

#2131 Fixed 'undef' warning with gcc and clang
  srtcore/platform_sys.h
Labels: Type: Bug, [core]

#2134 [docs] Updated SRTO_RETRANSMITALGO socket option description
  docs/API/API-socket-options.md
Labels: Type: Maintenance, [docs]

#2135 [build] Fixed CMake warning about string
  scripts/iOS.cmake
Labels: Type: Maintenance, [build]

#2137 Fixing 'atomic' linking for iOS target
  CMakeLists.txt
  scripts/CheckCXXAtomic.cmake
  scripts/CheckGCCAtomicIntrinsics.cmake
  scripts/FindPThreadGetSetName.cmake
  scripts/UnSetVariableFull.cmake
Labels: Type: Bug, [build]

#2136 Add iOS build to GitHub Actions CI
  .github/workflows/iOS.yaml
Labels: Type: Enhancement, [build]

#2140 [build] Fix build Android with NDK <17.
  CMakeLists.txt
  scripts/CheckGCCAtomicIntrinsics.cmake
Labels: Type: Bug, [build]

#2139 Fixed group drift synchronization
  srtcore/buffer.cpp
  srtcore/buffer.h
  srtcore/core.cpp
  srtcore/group.cpp
  srtcore/group.h
  srtcore/tsbpd_time.cpp
  srtcore/tsbpd_time.h
Labels: Type: Bug, [core]
